# 0. Sobre a base de dados

A base foi retirada do site [O Sistema de Estimativas de Emissões e Remoções de Gases de Efeito Estufa (SEEG)](https://seeg.eco.br), que é uma plataforma que contém uma das maiores bases de emissões de gases do efeito estufa no mundo.
A base retirada se refere aos dados na região brasileira.

In [10]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore", message="Unknown extension is not supported*")

In [11]:
url = ".\\1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx"
dados_emissoes = pd.read_excel(url, sheet_name= 'GEE Estados')

In [12]:
dados_emissoes.head()

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Processos Industriais,Indústria Química,Produção de ABS,NaN,NaN,NaN,Emissão,COVNM (t),SP,OUTRA_IND,...,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600,897.600
1,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,N2O (t),SP,OUTRA_IND,...,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000,130.000
2,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO (t),SP,OUTRA_IND,...,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576,1380.576
3,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,NOx (t),SP,OUTRA_IND,...,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430,431.430
4,Processos Industriais,Indústria Química,Produção de Ácido Adípico,NaN,NaN,NaN,Emissão,CO2e (t) GWP-AR2,SP,OUTRA_IND,...,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000,40300.000

In [13]:
dados_emissoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103312 entries, 0 to 103311
Data columns (total 63 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Nível 1 - Setor             103312 non-null  object
 1   Nível 2                     103312 non-null  object
 2   Nível 3                     103253 non-null  object
 3   Nível 4                     90920 non-null   object
 4   Nível 5                     100788 non-null  object
 5   Nível 6                     97691 non-null   object
 6   Emissão / Remoção / Bunker  103312 non-null  object
 7   Gás                         103312 non-null  object
 8   Estado                      97374 non-null   object
 9   Atividade Econômica         102076 non-null  object
 10  Produto                     37413 non-null   object
 11  1970                        103312 non-null  float64
 12  1971                        103312 non-null  float64
 13  1972                        103312 non-null  float64
 14  1973                        103312 non-null  float64
 15  1974                        103312 non-null  float64
 16  1975                        103312 non-null  float64
 17  1976                        103312 non-null  float64
 18  1977                        103312 non-null  float64
 19  1978                        103312 non-null  float64
 20  1979                        103312 non-null  float64
 21  1980                        103312 non-null  float64
 22  1981                        103312 non-null  float64
 23  1982                        103312 non-null  float64
 24  1983                        103312 non-null  float64
 25  1984                        103312 non-null  float64
 26  1985                        103312 non-null  float64
 27  1986                        103312 non-null  float64
 28  1987                        103312 non-null  float64
 29  1988                        103312 non-null  float64
 30  1989                        103312 non-null  float64
 31  1990                        103312 non-null  float64
 32  1991                        103312 non-null  float64
 33  1992                        103312 non-null  float64
 34  1993                        103312 non-null  float64
 35  1994                        103312 non-null  float64
 36  1995                        103312 non-null  float64
 37  1996                        103312 non-null  float64
 38  1997                        103312 non-null  float64
 39  1998                        103312 non-null  float64
 40  1999                        103312 non-null  float64
 41  2000                        103312 non-null  float64
 42  2001                        103312 non-null  float64
 43  2002                        103312 non-null  float64
 44  2003                        103312 non-null  float64
 45  2004                        103312 non-null  float64
 46  2005                        103312 non-null  float64
 47  2006                        103312 non-null  float64
 48  2007                        103312 non-null  float64
 49  2008                        103312 non-null  float64
 50  2009                        103312 non-null  float64
 51  2010                        103312 non-null  float64
 52  2011                        103312 non-null  float64
 53  2012                        103312 non-null  float64
 54  2013                        103312 non-null  float64
 55  2014                        103312 non-null  float64
 56  2015                        103312 non-null  float64
 57  2016                        103312 non-null  float64
 58  2017                        103312 non-null  float64
 59  2018                        103312 non-null  float64
 60  2019                        103312 non-null  float64
 61  2020                        103312 non-null  float64
 62  2021                        103312 non-null  float64
dtypes: float64(52), object(11)
memory usage: 49.7+ MB

# 1. Tratamento de dados

Importante ter algumas noções dos dados que são apresentados na planilha do excel:

1. Remoções são os dados referentes a retirada do efeito estufa.
2. NCI são dados não contemplados no inventário nacional.
3. Bunkers são emissões de transporte marítmo e aéreo, o que não condiz com a emissão diretas dos estados.

In [14]:
dados_emissoes['Emissão / Remoção / Bunker'].unique()

array(['Emissão', 'Emissão NCI', 'Remoção NCI', 'Bunker', 'Remoção'],
      dtype=object)

In [15]:
dados_emissoes[dados_emissoes["Emissão / Remoção / Bunker"].isin(["Remoção NCI","Remoção"])]

,Nível 1 - Setor,Nível 2,Nível 3,Nível 4,Nível 5,Nível 6,Emissão / Remoção / Bunker,Gás,Estado,Atividade Econômica,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23520,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RO,PEC,...,-1.434540e+07,-1.499358e+07,-1.543196e+07,-1.567070e+07,-1.630063e+07,-1.702215e+07,-1.740074e+07,-1.771914e+07,-1.767632e+07,-1.838895e+07
23521,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AC,PEC,...,-5.382949e+06,-5.524659e+06,-5.632429e+06,-5.765030e+06,-5.867354e+06,-5.942076e+06,-6.022000e+06,-6.002147e+06,-6.035591e+06,-6.459079e+06
23522,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),AM,PEC,...,-3.450455e+06,-3.540294e+06,-3.545724e+06,-3.924546e+06,-4.626541e+06,-4.874199e+06,-4.849173e+06,-4.959540e+06,-5.106806e+06,-5.809814e+06
23523,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),RR,PEC,...,-1.260166e+06,-1.261895e+06,-1.371664e+06,-1.501452e+06,-1.507705e+06,-1.509919e+06,-1.609826e+06,-1.616980e+06,-1.518397e+06,-1.926000e+06
23524,Agropecuária,Solos Manejados,Diretas,Variação dos Estoques de Carbono no Solo,Vegetal,Pastagem Bem Manejada,Remoção NCI,CO2 (t),PA,PEC,...,-3.429279e+07,-3.317185e+07,-3.281628e+07,-3.350720e+07,-3.557183e+07,-3.755308e+07,-4.134614e+07,-4.229403e+07,-4.275448e+07,-4.443440e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102751,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR4,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102752,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MT,AGROPEC,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102753,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR5,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05
102754,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MT,AGROPEC,...,-9.523000e+03,-9.667000e+03,-1.000300e+04,-1.024200e+04,-1.027200e+04,-1.019100e+04,-1.046900e+04,-1.090400e+04,-1.104100e+04,-1.109500e+04
102755,Mudança de Uso da Terra e Floresta,Remoção por Vegetação Secundária,Pantanal,em Área Protegida,Vegetação nativa estável,Vegetação não florestal secundária -- Vegetaçã...,Remoção,CO2e (t) GWP-AR6,MS,AGROPEC,...,-7.513000e+04,-7.911900e+04,-8.695900e+04,-9.201400e+04,-9.149400e+04,-9.630200e+04,-9.202000e+04,-9.762300e+04,-1.015020e+05,-1.008910e+05

In [17]:
dados_emissoes.loc[dados_emissoes["Emissão / Remoção / Bunker"].isin(["Remoção NCI","Remoção"]), 1970:2021].max()

1970    0.0
1971    0.0
1972    0.0
1973    0.0
1974    0.0
1975    0.0
1976    0.0
1977    0.0
1978    0.0
1979    0.0
1980    0.0
1981    0.0
1982    0.0
1983    0.0
1984    0.0
1985    0.0
1986    0.0
1987    0.0
1988    0.0
1989    0.0
1990    0.0
1991    0.0
1992    0.0
1993    0.0
1994    0.0
1995    0.0
1996    0.0
1997    0.0
1998    0.0
1999    0.0
2000    0.0
2001    0.0
2002    0.0
2003    0.0
2004    0.0
2005    0.0
2006    0.0
2007    0.0
2008    0.0
2009    0.0
2010    0.0
2011    0.0
2012    0.0
2013    0.0
2014    0.0
2015    0.0
2016    0.0
2017    0.0
2018    0.0
2019    0.0
2020    0.0
2021    0.0
dtype: float64

In [18]:
dados_emissoes.loc[dados_emissoes["Emissão / Remoção / Bunker"] == "Bunker", "Estado"].unique()

array([nan], dtype=object)